spring.application.name=Potato_Spring
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://gguip7554.cafe24.com:3306/gguip7554
spring.datasource.username=gguip7554
spring.datasource.password=p7554!potato

spring.jpa.database-platform: org.hibernate.dialect.MariaDBDialect
spring.jpa.open-in-view: false
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update